name = "Oasis 1.16.5"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf0b8561db7fb4eb19efaa56154d48cf33e68bbe9d4daad84105c5dc5771ec67"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
