name = "Oasis 1.16.5"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "034e20f8a5a5ea27eb7f8203ab56ee8221f94bde72b343ecf37921f3a2234add"

[versions]
forge = "36.2.35"
minecraft = "1.16.5"
