name = "Oasis 1.16.5"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbf5550d7cf6f4b1a7b3171d79f571ee75df0e74aa374053daa23cf39ac190e1"

[versions]
forge = "36.2.35"
minecraft = "1.16.5"
